#######################################
##  Dockerfile for Android RE Setup  ##
##  Based on Ubuntu (For now)        ##
#######################################

FROM ubuntu
MAINTAINER TylerBoire

RUN apt-get update && apt-get upgrade -y \
	install ia32-libs \
	install default-jdk \
	install default-jre \

RUN wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool && chmod +x /usr/local/bin/apktool
RUN wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.3.0.jar -O /usr/local/bin/apktool.jar && chmod +x /usr/local/bin/apktool.jar

RUN cd /tmp
RUN wget https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui_1.4.0-0_all.deb
RUN dpkg -i jd-gui_1.4.0-0_all.deb

RUN wget https://bitbucket.org/pxb1988/dex2jar/downloads/dex2jar-2.0.zip
RUN unzip dex2jar-2.0.zip -d /usr/local/bin/
RUN chmod 775 /usr/local/bin/d2j*
RUN chmod 775 /usr/local/bin/lib/

